directive @key(selectionSet: String!) on OBJECT
directive @computed(selectionSet: String!) on FIELD_DEFINITION
directive @merge(
  argsExpr: String
  keyArg: String
  keyField: String
  key: [String!]
  additionalArgs: String
) on FIELD_DEFINITION
directive @canonical on OBJECT | INTERFACE | INPUT_OBJECT | UNION | ENUM | SCALAR | FIELD_DEFINITION | INPUT_FIELD_DEFINITION

extend type Query {
  _sdl: String!
  _sdlVersion: String!
}
