query Locations(
  $skipBosses: Boolean = false
  $includeReviews: Boolean = false
) {
  locations {
    id
    name
    bosses @skip(if: $skipBosses) {
      id
      name
      reviews @include(if: $includeReviews) {
        difficulty
      }
    }
  }
}
